### ISSUE TITLE
How to force a client to disconnect from the server?

### ISSUE THREAD

**Issue by ricardovf** [fanout/node-grip#10]
Im using WebSocket over HTTP and we have devices connected that for some reason might have to be forced to disconnect from the websocket (pushpin). How can i do it?
Tried this without success:

`````
expressGrip.publish(
      connectionId,
      new grip.WebSocketMessageFormat(
        JSON.stringify({ action: 'close', code: 1013 }),
      ),
    );
``````
any tips?

**Comment by jkarneges** [comment]
Hmm, it looks like `WebSocketMessageFormat` needs to be updated to support the close action. In the meantime, you could create your own format class using `HttpStreamFormat` as a reference. Just make sure `name()` returns `ws-message`.

Note that you'll have to publish to a channel the connection is listening on. If you want to be able to publish using the connection ID, then have every connection subscribe to a channel derived from its own ID.

**Comment by ricardovf** [comment]
Thanks for the quick answer! Yes, i subscribe everyone to a room with the connection id.

It worked! Thanks a lot:

`````
export class PushpinCloseMessage {
  name() {
    return 'ws-message';
  }
  export() {
    return { action: 'close' };
  }
}
`````

`````
expressGrip.publish(connectionId, new PushpinCloseMessage());
`````

**Comment by jkarneges** [comment]
And this feature has now been added to `WebSocketMessageFormat` :)

**Comment by ricardovf** [comment]
@jkarneges In the same sense as the close action, how can i make the client subscribe or unsubscribe a channel, not when he is opening the connection.

I did this:

`````
import * as grip from 'grip';

export class PushpinSubscribeMessage {
  constructor(channel: string) {
    return new grip.WebSocketEvent(
      `c:{"type": "subscribe", "channel": "${channel}"}`
    );
  }
}
`````

It works, but the client also gets the message. Is there another way where the client does not get the message or i just have to ignore it.

**Comment by jkarneges** [comment]
Pushpin doesn't support receiving control messages through the publishing interface. This is partly because publishing is best-effort, and missing a control message could be problematic.

The official way to spontaneously send a control message is to trigger a refresh using a [ZeroMQ call](https://pushpin.org/docs/advanced/#refresh). This will cause Pushpin to immediately make a WebSocket-over-HTTP request. Then the response from your handler can contain control messages as necessary.

In order for your handler to know whether to send any control messages, you might want to keep [some state](https://pushpin.org/docs/protocols/websocket-over-http/#state-management) with the connection. This way, regardless of why Pushpin sent a request (whether because of the refresh call or because the client sent something), you only send control messages if actually needed.

**Comment by ricardovf** [comment]
So as i see it's not an easy task to include and exclude a connection from channels, because the only moment to include a connection in a channel is when the connection is opening, is that it or i understood wrong, i could send control message in the response of a regular message, after the connection is already opened?

**Comment by ricardovf** [comment]
And another questions, is there a way to know to what channels a connectionId is associated?

**Comment by jkarneges** [comment]
You can send control messages in any of the responses.

Pushpin does not provide a way for you to know what channels a connection is subscribed to. But, you could save whatever you need in connection metadata and refer to it in subsequent requests. See my earlier link.
